### ISSUE TITLE
Not part of Shiraz

### ISSUE THREAD

**Issue by dnebauer** [kookma/Refnotes#2]
The page [https://kookma.github.io/Refnotes/]() states "Refnotes is part of Shiraz plugin". This does not appear to be true at the current time -- Shiraz does not contain the `fnote` and `ref` macros that Refnotes does.

**Comment by kookma** [comment]
@dnebauer 
Yes, you are right. It is part of new release. It is postponed by **early March 2019**. Sorry for inconvenience.

**Comment by dnebauer** [comment]
No problem for me, as it had an unexpected beneficial side effect. I installed Shiraz because I wanted the Refnotes functionality. By the time I figured out I needed to install Refnotes as well, I'd found parts of Shiraz that fitted perfectly with my workflow and made it easier. Thanks for them both!

When you do add Refnotes to Shiraz, please include clear upgrade instructions for folks like me who already have them both installed.
