### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by ayeerr** [kookma/Refnotes#36]
First of all. This is a very helpful plugin. Thanks for developing this.

I am new to this and have installed the Bibtex and Refnotes plugins. After adding a reference, I tried using the ref macro. Not sure why, but I am getting this in terms of the narrative citation. I am guessing this is some silly thing I am overlooking. 

code used
`<<ref forbes_challenges_2011 n>>`
output 

> (Undefined widget 'let', 2011)

Thanks
ayeerr

**Comment by kookma** [comment]
What is the version Tiddlywiki you use?

Refnotes needs Tiddlywiki 5.2.0+

If you are on older version download an older version of Refnotes.

By the way, first test on the online Refnotes demo

**Comment by ayeerr** [comment]
I am using Tiddlywiki 5.2.0. However, I tried to use the newest version 5.2.2 and It seems to work fine in 5.2.2. Do you mean to say that it will work with 5.2.0 or not ? 

Further I also tested this in the online demo and it seemed to work fine. 

Thanks
ayeerr

**Comment by kookma** [comment]
Its actually TW 5.2.1 when $let was added.

See https://tiddlywiki.com/prerelease/#Release%205.2.1
